---
- name: add healthmonitor
  avi_healthmonitor:
    controller: "{{ avi_device }}"
    username: "{{ avi_username }}"
    password: "{{ avi_password }}"
    api_version: 17.1
    https_monitor:
      http_request: HEAD / HTTP/1.0
      http_response_code:
        - HTTP_2XX
        - HTTP_3XX
    receive_timeout: 4
    failed_checks: 3
    send_interval: 10
    successful_checks: 3
    type: HEALTH_MONITOR_HTTPS
    name: MyWebsite-HTTPS